Update WF

diff --git a/.github/workflows/models-check.yml b/.github/workflows/models-check.yml
--- a/.github/workflows/models-check.yml
+++ b/.github/workflows/models-check.yml
@@ -38,13 +38,16 @@ jobs:
           modified_models=$(git diff --name-only origin/${{ github.base_ref }} -- models | grep -E '\.cs$')
           if [ -n "$modified_models" ]; then
             for model in $modified_models; do
-              model_name=$(basename "$model" .cs)
               lines_removed_or_modified=$(git diff origin/${{ github.base_ref }} -- "$model" | grep '^-' | grep -v '^---' | grep -v '^-\s*//'| grep -v '^\s*$' | wc -l)
               if [ "$lines_removed_or_modified" -gt 0 ]; then
-                echo "Error: Model $model_name was modified. Please review the changes."
-                exit 1
+                model_name=$(basename "$model" .cs)
+                modified_list+=("$model_name")
               fi
             done
+          fi
+          if [ ${#modified_list[@]} -gt 0 ]; then
+            echo "Error: The following models have modified or deleted properties: ${modified_list[*]}"
+            exit 1
           fi
               
       - name: Passed 
