test

diff --git a/.github/workflows/models-check.yml b/.github/workflows/models-check.yml
--- a/.github/workflows/models-check.yml
+++ b/.github/workflows/models-check.yml
@@ -16,25 +16,25 @@ jobs:
           fetch-depth: 0
           
       - name: Fetch main branch
-        run: git fetch origin main
+        run: git fetch origin main      
 
-      - name: Check for deleted models and fail if any are found
-        run: |
-          echo "Checking for deleted models..."
-          deleted_models=$(git diff --name-status origin/main -- models | grep '^D' | cat -A || true)
-          echo "Deleted models: $deleted_models"
-          deleted_count=$(echo "$deleted_models" | wc -l)
-          echo "Number of deleted models: $deleted_count"
+      # - name: Check for deleted models and fail if any are found
+      #   run: |
+      #     echo "Checking for deleted models..."
+      #     deleted_models=$(git diff --name-status origin/main -- models | grep '^D' | cat -A || true)
+      #     echo "Deleted models: $deleted_models"
+      #     deleted_count=$(echo "$deleted_models" | wc -l)
+      #     echo "Number of deleted models: $deleted_count"
 
-          if [ "$deleted_count" -gt 0 ]; then
-            echo "BREAKING CHANGE: Please review the changes. The following models were deleted or renamed:"
-            echo "$deleted_models" | while read -r status file; do
-              echo "- $file"
-            done
-            exit 1
-          else
-            echo "No models were deleted."
-          fi
+      #     if [ "$deleted_count" -gt 0 ]; then
+      #       echo "BREAKING CHANGE: Please review the changes. The following models were deleted or renamed:"
+      #       echo "$deleted_models" | while read -r status file; do
+      #         echo "- $file"
+      #       done
+      #       exit 1
+      #     else
+      #       echo "No models were deleted."
+      #     fi
 
       - name: Check for deleted or modified properties in the models
         run: |
